################################# Default configuration ###################
# provide your domain here
baseURL = "https://n-mydocs.netlify.com/"
# theme
theme = "dot"
# site title
title = "My docs"
# desable language
disableLanguages = []
defaultContentLanguage = "ja"
pygmentsUseClasses = true
pygmentsCodefences = true
############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
secondary_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"

# font family
font_family = "Source Sans Pro" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

mathjaxStyle = "mathjax-style.css"
############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-vimeo-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################# navigation ################################
# Dropdown menu
[[menu.main]]
weight = 1
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "MATH"
  url = "math"
  weight = 1

  [[menu.main]]
  parent = "docs"
  name = "ML"
  url = "ml"
  weight = 2

  [[menu.main]]
  parent = "docs"
  name = "PROGRAMING"
  url = "programing"
  weight = 3

  [[menu.main]]
  parent = "docs"
  name = "OTHER"
  url = "other"
  weight = 4


################################ English Language ######################
[Languages.ja]
languageName = "Ja"
languageCode = "ja-jp"
weight = 1
home = "Home"
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.ja.params.banner]
title = "My Docs"
description = ""
bg_image = "images/banner.jpg"
placeholder = "Search"

# call to action
# [Languages.ja.params.cta]
# enable = true
# title = "Didn't find an answer to your question?"
# description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# [Languages.ja.params.cta.button]
# enable = true
# label = "contact us"
# link = "contact"
